# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_joint
      - upper_arm_joint
      - elbow_joint
      - wrist_joint
      - ee_rotation_joint_x
      - ee_rotation_joint_z
    action_ns: follow_joint_trajectory
    default: true